// Code generated by MockGen. DO NOT EDIT.
// Source: ../caller/car.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCarInterface is a mock of CarInterface interface
type MockCarInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCarInterfaceMockRecorder
}

// MockCarInterfaceMockRecorder is the mock recorder for MockCarInterface
type MockCarInterfaceMockRecorder struct {
	mock *MockCarInterface
}

// NewMockCarInterface creates a new mock instance
func NewMockCarInterface(ctrl *gomock.Controller) *MockCarInterface {
	mock := &MockCarInterface{ctrl: ctrl}
	mock.recorder = &MockCarInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCarInterface) EXPECT() *MockCarInterfaceMockRecorder {
	return m.recorder
}

// SpeedUp mocks base method
func (m *MockCarInterface) SpeedUp() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpeedUp")
	ret0, _ := ret[0].(int)
	return ret0
}

// SpeedUp indicates an expected call of SpeedUp
func (mr *MockCarInterfaceMockRecorder) SpeedUp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpeedUp", reflect.TypeOf((*MockCarInterface)(nil).SpeedUp))
}
